CREATE TABLE "channel" (
  "channel_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "channel_name" varchar(255) NOT NULL,
  "admin_id" varchar(255) NOT NULL
);

CREATE TABLE "message" (
  "message_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "channel_id" int NOT NULL,
  "user_id" varchar(255) NOT NULL,
  "sent_at" timestamp NOT NULL,
  "text" varchar(255) NOT NULL
);

CREATE INDEX ON "message" ("channel_id");

ALTER TABLE "message" ADD FOREIGN KEY ("channel_id") REFERENCES "channel" ("channel_id");
