name: database_update
run-name: Setting up channels-database
on:
  push:
    branches:
      - main
jobs:
  connect-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Show tables
        run: PGPASSWORD=${{ secrets.ELEPHANT_PASSWORD }} psql -h ${{ secrets.ELEPHANT_HOSTNAME }} -p 5432 -d tepudsxx -U ${{ secrets.ELEPHANT_USERNAME }} -c "\dt"